### PR TITLE
Fix type meta info in token files

### LINKED ISSUE #1619: [v2] token file without type metadata
**Describe the bug**
When creating a token file, said file does not include the type metadata associated with AccessGrants.

**How To Reproduce**

```
skupper token north north.yaml
```

**Expected behavior**
The file `north.yaml` includes the following data at the beginning of the file:

```
apiVersion: skupper.io/v1alpha1
kind: AccessToken
```

**Environment details**
 - Skupper CLI: V2

### PR DESCRIPTION
**Pull request by nluaces**
Fixes #1619

### CODE REVIEW

File: internal/cmd/skupper/token/kube/token_issue.go [hunk 1]
```diff
@@ -173,6 +173,11 @@ func (cmd *CmdTokenIssue) WaitUntil() error {
 		}
 
 		if token != nil && token.IsReady() {
+			token.TypeMeta = metav1.TypeMeta{
+				APIVersion: "skupper.io/v1alpha1",
+				Kind:       "AccessGrant",
```
Comment (fgiorgetti) [inline internal/cmd/skupper/token/kube/token_issue.go:178]: Should it be AccessToken?

**Review by lynnemorrison — APPROVED** [review]

File: internal/cmd/skupper/token/kube/token_issue.go (hunk 1 above)
Comment (lynnemorrison) [reply internal/cmd/skupper/token/kube/token_issue.go:178]: I think that makes sense.

Comment (nluaces) [reply internal/cmd/skupper/token/kube/token_issue.go:178]: @lynnemorrison the code in token_redeem is reading the file as an AccessGrant to covert it later as an AccessToken (https://github.com/skupperproject/skupper/blob/46036fcdb2f8d34a4d45f867a56286d453d1f89a/internal/cmd/skupper/token/kube/token_redeem.go#L123)...

Will change that in both places.

**Review by lynnemorrison — APPROVED** [review]

**Review by fgiorgetti — APPROVED** [review]
