### PR TITLE
Change commands to query the collector-lite

### LINKED ISSUE #798: Skupper  network status doesn't work with a large number of sites
## Summary 
When multiple sites are linked, the API call to retrieve the VAN information starts to fail. 

## How to reproduce (with a controlled environment and local connections)
1. One OSP cluster with the following infra:
1.1 - 3 Master Nodes + 3 Worker Nodes
1.2 - Flavor: ci.m1.xlarge 
```
+----------------------------+-----------------------------------------------------------+
| Field                      | Value                                                     |
+----------------------------+-----------------------------------------------------------+
| OS-FLV-DISABLED:disabled   | False                                                     |
| OS-FLV-EXT-DATA:ephemeral  | 0                                                         |
| access_project_ids         | None                                                      |
| description                | None                                                      |
| disk                       | 40                                                        |
| id                         | 371256e2-891f-4b5a-9f8f-526608217b8d                      |
| name                       | ci.m1.xlarge                                              |
| os-flavor-access:is_public | True                                                      |
| properties                 | aggregate_instance_extra_specs:server_type:aggregate='ci' |
| ram                        | 16384                                                     |
| rxtx_factor                | 1.0                                                       |
| swap                       |                                                           |
| vcpus                      | 8                                                         |
+----------------------------+-----------------------------------------------------------+
```
2. Linking 5 sites into a single site and getting the site data inside the service-controller pod
2.1 Command to extract the data and measure the time: `kubectl exec -n zago-site1 -it deploy/skupper-service-controller -- bash -c 'time get sites'`
2.2 With 5 sites, I was able to retrieve the data properly:
```
 INSIDE 02,ID                                   NAME       EDGE  VERSION NAMESPACE  URL                                                                           CONNECTED TO
76165630-843a-4706-9fd6-4bbfc1c15a08 zago-site1 false 1.0.2   zago-site1 skupper-inter-router-zago-site1.apps.ocp410.interconnect.app-services-dev.net 

real    0m0.032s
user    0m0.004s
sys     0m0.005s
 INSIDE 03,ID                                   NAME       EDGE  VERSION NAMESPACE  URL                                                                           CONNECTED TO
76165630-843a-4706-9fd6-4bbfc1c15a08 zago-site1 false 1.0.2   zago-site1 skupper-inter-router-zago-site1.apps.ocp410.interconnect.app-services-dev.net 
9f9d2bda-41cf-4ec0-a4e9-b3e525ccd7f9 zago-site2 false 1.0.2   zago-site2                                                                               76165630-843a-4706-9fd6-4bbfc1c15a08

real    0m0.065s
user    0m0.001s
sys     0m0.005s
 INSIDE 04,ID                                   NAME       EDGE  VERSION NAMESPACE  URL                                                                           CONNECTED TO
76165630-843a-4706-9fd6-4bbfc1c15a08 zago-site1 false 1.0.2   zago-site1 skupper-inter-router-zago-site1.apps.ocp410.interconnect.app-services-dev.net 
9f9d2bda-41cf-4ec0-a4e9-b3e525ccd7f9            false 1.0.2                                                                                            76165630-843a-4706-9fd6-4bbfc1c15a08
d175e0db-be9b-431e-aecc-b5f96e6e3979            false 1.0.2                                                                                            76165630-843a-4706-9fd6-4bbfc1c15a08

real    0m10.081s
user    0m0.003s
sys     0m0.005s
 INSIDE 05,ID                                   NAME       EDGE  VERSION NAMESPACE  URL                                                                           CONNECTED TO
80e4e83c-5f03-46ff-9f4f-3f752baf4f83 zago-site4 false 1.0.2   zago-site4                                                                               76165630-843a-4706-9fd6-4bbfc1c15a08
76165630-843a-4706-9fd6-4bbfc1c15a08 zago-site1 false 1.0.2   zago-site1 skupper-inter-router-zago-site1.apps.ocp410.interconnect.app-services-dev.net 
9f9d2bda-41cf-4ec0-a4e9-b3e525ccd7f9 zago-site2 false 1.0.2   zago-site2                                                                               76165630-843a-4706-9fd6-4bbfc1c15a08
d175e0db-be9b-431e-aecc-b5f96e6e3979 zago-site3 false 1.0.2   zago-site3                                                                               76165630-843a-4706-9fd6-4bbfc1c15a08

real    0m0.198s
user    0m0.001s
sys     0m0.006s
 INSIDE 06,ID                                   NAME       EDGE  VERSION NAMESPACE  URL                                                                           CONNECTED TO
9f9d2bda-41cf-4ec0-a4e9-b3e525ccd7f9 zago-site2 false 1.0.2   zago-site2                                                                               76165630-843a-4706-9fd6-4bbfc1c15a08
d175e0db-be9b-431e-aecc-b5f96e6e3979 zago-site3 false 1.0.2   zago-site3                                                                               76165630-843a-4706-9fd6-4bbfc1c15a08
80e4e83c-5f03-46ff-9f4f-3f752baf4f83 zago-site4 false 1.0.2   zago-site4                                                                               76165630-843a-4706-9fd6-4bbfc1c15a08
d5e67bd7-0301-489c-b99d-dabb79584d2d zago-site5 false 1.0.2   zago-site5                                                                               76165630-843a-4706-9fd6-4bbfc1c15a08
76165630-843a-4706-9fd6-4bbfc1c15a08 zago-site1 false 1.0.2   zago-site1 skupper-inter-router-zago-site1.apps.ocp410.interconnect.app-services-dev.net 
```
3. Linking 10 more sites into the existing Skupper network (A total of 15 sites now) 
3.1 With this amount of sites, the command is still able to return the data correctly:
```
ID                                   NAME        EDGE  VERSION NAMESPACE   URL                                                                           CONNECTED TO
b445d07a-40a1-4726-bb4d-7672fa223679 zago-site11 false 1.0.2   zago-site11                                                                               76165630-843a-4706-9fd6-4bbfc1c15a08
d7693a78-26a2-4037-bb9f-fbd10e082b4b zago-site8  false 1.0.2   zago-site8                                                                                76165630-843a-4706-9fd6-4bbfc1c15a08
c7f77517-e58c-46d2-88d0-12af7762fdb6 zago-site10 false 1.0.2   zago-site10                                                                               76165630-843a-4706-9fd6-4bbfc1c15a08
d1664f66-7aa3-4e03-9ca8-65d1e37ac5c6 zago-site14 false 1.0.2   zago-site14                                                                               76165630-843a-4706-9fd6-4bbfc1c15a08
da62c736-16df-4577-9eaf-b68d620ab21a zago-site9  false 1.0.2   zago-site9                                                                                76165630-843a-4706-9fd6-4bbfc1c15a08
37913e92-ba3b-4573-ab57-56898cb7d406 zago-site12 false 1.0.2   zago-site12                                                                               76165630-843a-4706-9fd6-4bbfc1c15a08
1518c204-e750-4f80-a698-1f1e70a4d572 zago-site15 false 1.0.2   zago-site15                                                                               76165630-843a-4706-9fd6-4bbfc1c15a08
9f9d2bda-41cf-4ec0-a4e9-b3e525ccd7f9 zago-site2  false 1.0.2   zago-site2                                                                                76165630-843a-4706-9fd6-4bbfc1c15a08
d175e0db-be9b-431e-aecc-b5f96e6e3979 zago-site3  false 1.0.2   zago-site3                                                                                76165630-843a-4706-9fd6-4bbfc1c15a08
d5e67bd7-0301-489c-b99d-dabb79584d2d zago-site5  false 1.0.2   zago-site5                                                                                76165630-843a-4706-9fd6-4bbfc1c15a08
5414c44b-1d63-4882-b036-7e477b7b354f zago-site7  false 1.0.2   zago-site7                                                                                76165630-843a-4706-9fd6-4bbfc1c15a08
76165630-843a-4706-9fd6-4bbfc1c15a08 zago-site1  false 1.0.2   zago-site1  skupper-inter-router-zago-site1.apps.ocp410.interconnect.app-services-dev.net 
80e4e83c-5f03-46ff-9f4f-3f752baf4f83 zago-site4  false 1.0.2   zago-site4                                                                                76165630-843a-4706-9fd6-4bbfc1c15a08
b5a8004a-6743-4ba5-a7d9-6616e8715397 zago-site6  false 1.0.2   zago-site6                                                                                76165630-843a-4706-9fd6-4bbfc1c15a08
684d0fcd-241a-4f16-8f19-dbcb911ad922 zago-site13 false 1.0.2   zago-site13                                                                               76165630-843a-4706-9fd6-4bbfc1c15a08
```
4. When I added the 23rd site, the command didn't return all the sites:
4.1 Data
```
37913e92-ba3b-4573-ab57-56898cb7d406 zago-site12 false 1.0.2   zago-site12                                                                               76165630-843a-4706-9fd6-4bbfc1c15a08
1518c204-e750-4f80-a698-1f1e70a4d572 zago-site15 false 1.0.2   zago-site15                                                                               76165630-843a-4706-9fd6-4bbfc1c15a08
d7693a78-26a2-4037-bb9f-fbd10e082b4b zago-site8  false 1.0.2   zago-site8                                                                                76165630-843a-4706-9fd6-4bbfc1c15a08
684d0fcd-241a-4f16-8f19-dbcb911ad922 zago-site13 false 1.0.2   zago-site13                                                                               76165630-843a-4706-9fd6-4bbfc1c15a08
d1664f66-7aa3-4e03-9ca8-65d1e37ac5c6 zago-site14 false 1.0.2   zago-site14                                                                               76165630-843a-4706-9fd6-4bbfc1c15a08
b1ec2b46-f269-4c4c-9fdf-fa9e52c2c0e7 zago-site16 false 1.0.2   zago-site16                                                                               76165630-843a-4706-9fd6-4bbfc1c15a08
55efefc1-542f-41b7-a709-e1da8635a324 zago-site17 false 1.0.2   zago-site17                                                                               76165630-843a-4706-9fd6-4bbfc1c15a08
9f9d2bda-41cf-4ec0-a4e9-b3e525ccd7f9 zago-site2  false 1.0.2   zago-site2                                                                                76165630-843a-4706-9fd6-4bbfc1c15a08
80e4e83c-5f03-46ff-9f4f-3f752baf4f83 zago-site4  false 1.0.2   zago-site4                                                                                76165630-843a-4706-9fd6-4bbfc1c15a08
c7f77517-e58c-46d2-88d0-12af7762fdb6 zago-site10 false 1.0.2   zago-site10                                                                               76165630-843a-4706-9fd6-4bbfc1c15a08
b445d07a-40a1-4726-bb4d-7672fa223679 zago-site11 false 1.0.2   zago-site11                                                                               76165630-843a-4706-9fd6-4bbfc1c15a08
2c7b1203-175b-4adb-99a7-268bfc39d306 zago-site19 false 1.0.2   zago-site19                                                                               76165630-843a-4706-9fd6-4bbfc1c15a08
55096e44-ad70-4c51-a5bb-b2368df8cc87 zago-site20 false 1.0.2   zago-site20                                                                               76165630-843a-4706-9fd6-4bbfc1c15a08
b5a8004a-6743-4ba5-a7d9-6616e8715397 zago-site6  false 1.0.2   zago-site6                                                                                76165630-843a-4706-9fd6-4bbfc1c15a08
da62c736-16df-4577-9eaf-b68d620ab21a zago-site9  false 1.0.2   zago-site9                                                                                76165630-843a-4706-9fd6-4bbfc1c15a08
d5e67bd7-0301-489c-b99d-dabb79584d2d zago-site5  false 1.0.2   zago-site5                                                                                76165630-843a-4706-9fd6-4bbfc1c15a08
5414c44b-1d63-4882-b036-7e477b7b354f zago-site7  false 1.0.2   zago-site7                                                                                76165630-843a-4706-9fd6-4bbfc1c15a08
fad09a19-82b7-4000-846b-1c5807f2c971 zago-site18 false 1.0.2   zago-site18                                                                               76165630-843a-4706-9fd6-4bbfc1c15a08
a7b350d2-e4f1-4276-967e-c476e6d7a722 zago-site21 false 1.0.2   zago-site21                                                                               76165630-843a-4706-9fd6-4bbfc1c15a08
8b74f342-4d32-474f-ab46-04506273e6d5 zago-site22 false 1.0.2   zago-site22                                                                               76165630-843a-4706-9fd6-4bbfc1c15a08
76165630-843a-4706-9fd6-4bbfc1c15a08 zago-site1  false 1.0.2   zago-site1  skupper-inter-router-zago-site1.apps.ocp410.interconnect.app-services-dev.net 
d175e0db-be9b-431e-aecc-b5f96e6e3979             false 1.0.2                                                                                             76165630-843a-4706-9fd6-4bbfc1c15a0
```
4.2 From its point the command randomly returns data from the sites, adding more just increases the issue.

## Considerations
- The `skupper network status` just returns the local config from the site
- The site's info were retrieved from the skupper-service-controller pod, and the call is a HTTP get to: http://localhost:8181/sites
- The calls seem to be serialized by the skupper-service-controller, wouldn´t be better for each site to broadcast its info to all the VAN and therefore the controller to summarize the data?

### PR DESCRIPTION
**Pull request by nluaces**
**Note for testing:** this pull request has references to customized images in order to make it work with the collector-lite while it is not merged to main. The `images.go` file will be restored once the collector-lite is merged. It is still necessary to export the router image before `skupper init`:
```
export QDROUTERD_IMAGE=quay.io/skupper/skupper-router:main
```
**Commands affected by this change:**

- skupper network status
  - kubernetes: adapted to collector-lite and added new changes in the output
  - podman: no implementation. no changes.
- skupper status 
   - kubernetes: adapted to collector-lite and added verbose option  
   - podman: just added verbose option
- skupper link status 
   - kubernetes: adapted to collector-lite for incoming links. Those incoming links are shown by default again.
   - podman: no changes.
- skupper service status
   - kubernetes: adapted to collector lite and added new changes in the output
   - podman: no changes  

There are examples of the new outputs [here](https://gist.github.com/nluaces/56bea744fc34850ae2be39915bfe900c)

Fixes #798

### CODE REVIEW

File: pkg/images/images.go [hunk 1]
```diff
@@ -1,12 +1,12 @@
...
+	DefaultImageRegistry       string = "quay.io/nluaces"
 	RouterImageName            string = "skupper-router:main"
-	ServiceControllerImageName string = "service-controller:main"
+	ServiceControllerImageName string = "service-controller:collector-lite"
 	ControllerPodmanImageName  string = "controller-podman:main"
-	ConfigSyncImageName        string = "config-sync:main"
-	FlowCollectorImageName     string = "flow-collector:main"
+	ConfigSyncImageName        string = "config-sync:collector-lite"
+	FlowCollectorImageName     string = "flow-collector:collector-lite"
 	SiteControllerImageName    string = "site-controller:main"
```
Comment (grs) [inline pkg/images/images.go:10]: I'm assuming these changes were just for testing?

File: api/types/client.go [hunk 2]
```diff
@@ -294,7 +294,76 @@ type GatewayInspectResponse struct {
...
+	Protocol string `json:"protocol,omitempty"`
+	Address  string `json:"address,omitempty"`
+}
+
+type ConnectorInfo struct {
+	DestPort string `json:"destPort,omitempty"`
+	Address  string `json:"address,omitempty"`
+	Process  string `json:"process,omitempty"`
+	Target   string `json:"target,omitempty"`
+}
```
Comment (grs) [inline api/types/client.go:364]: Not a big issue, but to me it might be nice to have these new types in a different package. Perhaps in pkg/network for example?

**Review by grs — COMMENTED** [review]
Very nice work! Just a few minor comments or questions, but lgtm.

File: api/types/types.go [hunk 3]
```diff
@@ -28,11 +28,12 @@ import (
...
-	DefaultVanName      string = "skupper"
-	DefaultSiteName     string = "skupper-site"
-	ClusterLocalPostfix string = ".svc.cluster.local"
-	SiteConfigMapName   string = "skupper-site"
+	NamespaceDefault       string = "skupper"
+	DefaultVanName         string = "skupper"
+	DefaultSiteName        string = "skupper-site"
+	ClusterLocalPostfix    string = ".svc.cluster.local"
+	SiteConfigMapName      string = "skupper-site"
+	VanStatusConfigMapName string = "skupper-van-status"
```
[the remark this answers is not in the document]
Comment (ajssmith) [reply api/types/types.go:36]: Agree and name will be changed in concert with #1196

File: pkg/images/images.go (hunk 1 above)
Comment (grs) [reply pkg/images/images.go:10]: Note to self: read the description!

File: api/types/client.go (hunk 2 above)
Comment (nluaces) [reply api/types/client.go:364]: Yes, absolutely. Thanks!

File: pkg/network/network.go [hunk 4]
```diff
@@ -0,0 +1,146 @@
...
+	VanStatus *types.VanStatusInfo
+}
+
+func (s *SkupperStatus) GetServiceSitesMap() map[string][]types.SiteStatusInfo {
+
+	mapServiceSites := make(map[string][]types.SiteStatusInfo)
+
+	for _, site := range s.VanStatus.SiteStatus {
+
+		for _, listener := range site.RouterStatus[0].Listeners {
```
Comment (fgiorgetti) [inline pkg/network/network.go:21]: I have noticed that when a podman site is linked the `RouterStatus` slice is empty.
Maybe you could ignore sites with an empty RouterStatus slice for now.

File: pkg/network/network.go [hunk 5]
```diff
@@ -0,0 +1,146 @@
...
+	return mapServiceLabels
+}
+
+func (s *SkupperStatus) GetSiteTargetsMap() map[string]map[string]types.ConnectorInfo {
+
+	mapSiteTargets := make(map[string]map[string]types.ConnectorInfo)
+
+	for _, site := range s.VanStatus.SiteStatus {
+
+		for _, connector := range site.RouterStatus[0].Connectors {
```
Comment (fgiorgetti) [inline pkg/network/network.go:59]: Same here...

**Review by fgiorgetti — COMMENTED** [review]
A couple of minor comments, but overall it feels great!

File: api/types/types.go [hunk 6]
```diff
@@ -69,7 +70,7 @@ const (
 
 var TransportPolicyRule = []rbacv1.PolicyRule{
 	{
-		Verbs:     []string{"get", "list", "watch"},
+		Verbs:     []string{"get", "list", "watch", "create", "update"},
```
[the remark this answers is not in the document]
Comment (nluaces) [reply api/types/types.go]: Solved in 9dc6b33b76619c1cae966ee60fe0dd7ea25b7cba

File: api/types/types.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (nluaces) [reply api/types/types.go]: Solved in 9dc6b33b76619c1cae966ee60fe0dd7ea25b7cba

File: api/types/client.go (hunk 2 above)
Comment (nluaces) [reply api/types/client.go]: Solved in 68f66b2e5c69e3a9286832f7280c2938ebd36571

File: cmd/skupper/skupper_kube_network.go [hunk 7]
```diff
@@ -26,134 +24,96 @@ func (s *SkupperKubeNetwork) Platform() types.Platform {
...
 func (s *SkupperKubeNetwork) Status(cmd *cobra.Command, args []string) error {
-	silenceCobra(cmd)
 
-	if networkStatusTimeout.Seconds() <= 0 {
-		return fmt.Errorf(`invalid timeout value`)
-	}
+	silenceCobra(cmd)
 
-	ctx, cancel := context.WithTimeout(context.Background(), networkStatusTimeout)
+	ctx, cancel := context.WithTimeout(context.Background(), types.DefaultFlowTimeoutDuration)
```
[the remark this answers is not in the document]
Comment (nluaces) [reply cmd/skupper/skupper_kube_network.go]: Thanks, solved in 68d643a7dcd0ec5dde50a3aa787d690d912cd2f5

File: cmd/skupper/skupper_kube_site.go [hunk 8]
```diff
@@ -234,69 +233,83 @@ func (s *SkupperKubeSite) Status(cmd *cobra.Command, args []string) error {
...
-		}
-		policyStr := ""
-		if vanClient, ok := cli.(*client.VanClient); ok {
-			p := client.NewPolicyValidatorAPI(vanClient)
-			r, err := p.IncomingLink()
-			if err == nil && r.Enabled {
-				policyStr = " (with policies)"
-			}
+	if err != nil {
+		return err
```
[the remark this answers is not in the document]
Comment (nluaces) [reply cmd/skupper/skupper_kube_site.go]: Thanks! solved in 3a604a71e4c041c931d6e85e73e22d7f6da51dd6

File: cmd/skupper/skupper_link.go [hunk 9]
```diff
@@ -180,50 +174,36 @@ func NewCmdLinkStatus(skupperClient SkupperLinkClient) *cobra.Command {
...
-
-							if err != nil {
-								fmt.Println(err)
-								break
-							} else if len(remoteLinks) > 0 {
-								for _, remoteLink := range remoteLinks {
-									var nsStr string
-									if remoteLink.Namespace != "" {
-										nsStr = fmt.Sprintf("the namespace %s on site ", remoteLink.Namespace)
-									}
```
[the remark this answers is not in the document]
Comment (nluaces) [reply cmd/skupper/skupper_link.go:208]: Solved in 3a604a71e4c041c931d6e85e73e22d7f6da51dd6

File: pkg/network/network.go (hunk 4 above)
Comment (nluaces) [reply pkg/network/network.go]: Thanks! solved in 3371b9e46ea653a9f283ff1dd6c3bcff3e0ef4ae

File: pkg/network/network.go (hunk 5 above)
Comment (nluaces) [reply pkg/network/network.go]: Solved in 3371b9e46ea653a9f283ff1dd6c3bcff3e0ef4ae

**Review by grs — APPROVED** [review]

**Review by ajssmith — APPROVED** [review]
lgtm
