### PR TITLE
[kube] Check if credentials already exist before generating a link

### LINKED ISSUE #2005: Link generation fails with name conflict
**Describe the bug**

```
$ skupper link generate
certificates.skupper.io "link-west" already exists
-> 1
```

Generate commands don't create resources.  How can there be a conflict with something already existing?

Also, generated resources should have unique qualifiers: link-west-ac619.

**How To Reproduce**

Run "skupper link generate" twice.

**Environment details**

Skupper fb05630a (main, 14 March 2025)

### PR DESCRIPTION
**Pull request by nluaces**
- Fixes #2005
- Avoids printing the yaml separator (`---`) after printing the last resource, in order to make it compatible with the non-kube resource parser.

### CODE REVIEW

File: internal/cmd/skupper/link/link.go [hunk 1]
```diff
@@ -34,16 +34,16 @@ func CmdLinkGenerateFactory(configuredPlatform common.Platform) *cobra.Command {
 
 	cmdLinkGenerateDesc := common.SkupperCmdDescription{
 		Use:   "generate",
-		Short: "Generate a new link resource in a yaml file",
-		Long: `Generate a new link resource with the data needed from the target site. The resultant
+		Short: "Generate a new link resource and save it as a YAML file, unless explicitly specified otherwise using the `--output` flag.",
```
Comment (fgiorgetti) [inline internal/cmd/skupper/link/link.go:37]: It is not behaving as the description says. It is always displaying a YAML output.

Comment (nluaces) [reply internal/cmd/skupper/link/link.go:37]: "unless explicitly specified otherwise using the `--output` flag"?

Did not work with `-o json`?

Comment (fgiorgetti) [reply internal/cmd/skupper/link/link.go:37]: Yes, it works with json, but the description says: `Generate a new link resource and save it as a YAML file`.
Is it still a valid description?

Comment (nluaces) [reply internal/cmd/skupper/link/link.go:37]: My bad, you are right, it is not generating any file. Will change that now.

Comment (nluaces) [reply internal/cmd/skupper/link/link.go]: I have updated the description again, given that the -o flag is not available for non-kube.

**Review by fgiorgetti — APPROVED** [review]
