### PR TITLE
Fix deduction of ports for statefulset

### LINKED ISSUE #1379: StatefulSet / Headless missing exported port.
**Describe the bug**
Not all the port are exposed when using statefulset / headless
My Statefulset is composed of multiple container each of them exposing his own port.
For example in the yaml we can see that the container `yb-tserver` expose multiple port `9000,...`
and `yb-controller` expose `18018`.

If I specify all the port at the first container level, then the port is correctly exported, I suspect we only check the first container in the StatefulSet.

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    meta.helm.sh/release-name: ybjp2--northeast-1d-zlzk
    meta.helm.sh/release-namespace: yb-japan
    skupper.io/headless: "true"
    skupper.io/proxy: tcp
  creationTimestamp: "2024-01-31T08:00:40Z"
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: yb-tserver
    chart: yugabyte
    component: yugabytedb
    heritage: Helm
    release: ybjp2--northeast-1d-zlzk
  name: ybjp2--northeast-1d-zlzk-yb-tserver
  namespace: yb-japan
  resourceVersion: "280687"
  uid: bb3c49f7-23d3-4d50-92ba-4e6ad18d7508
spec:
  .....
  serviceName: ybjp2--northeast-1d-zlzk-yb-tservers
  ......
    spec:
      containers:
      - args:
       ...........
        command:
        - /sbin/tini
        - --
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: YBDEVOPS_CORECOPY_DIR
          value: /mnt/disk0/cores
        - name: SSL_CERTFILE
          value: /root/.yugabytedb/root.crt
        image: quay.io/yugabyte/yugabyte:2.20.1.3-b3
        imagePullPolicy: IfNotPresent
        lifecycle:
          postStart:
            exec:
              command:
              ....
        livenessProbe:
          exec:
            command:
            ......
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: yb-tserver
        ports:
        - containerPort: 9000
          name: http-ui
          protocol: TCP
        - containerPort: 12000
          name: http-ycql-met
          protocol: TCP
        - containerPort: 11000
          name: http-yedis-met
          protocol: TCP
        - containerPort: 13000
          name: http-ysql-met
          protocol: TCP
        - containerPort: 9100
          name: tcp-rpc-port
          protocol: TCP
        - containerPort: 6379
          name: tcp-yedis-port
          protocol: TCP
        - containerPort: 9042
          name: tcp-yql-port
          protocol: TCP
        - containerPort: 5433
          name: tcp-ysql-port
          protocol: TCP
        resources:
          limits:
            cpu: 2400m
            memory: 4Gi
          requests:
            cpu: "2"
            memory: 4Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        .....
      - args:
        ......
        command:
        - /sbin/tini
        - --
        env:
        - name: USER
          value: yugabyte
        image: quay.io/yugabyte/yugabyte:2.20.1.3-b3
        imagePullPolicy: IfNotPresent
        name: yb-cleanup
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /home/yugabyte/
          name: ybjp2--northeast-1d-zlzk-datadir0
          subPath: yb-data
        - mountPath: /var/yugabyte/cores
          name: ybjp2--northeast-1d-zlzk-datadir0
          subPath: cores
      - args:
        - /bin/bash
        - -c
        - |
          while true; do
            sleep 60;
            /home/yugabyte/tools/k8s_ybc_parent.py status || /home/yugabyte/tools/k8s_ybc_parent.py start;
          done
        command:
        - /sbin/tini
        - --
        image: quay.io/yugabyte/yugabyte:2.20.1.3-b3
        imagePullPolicy: IfNotPresent
        name: yb-controller
        ports:
        - containerPort: 18018
          name: grpc-ybc-port
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: tserver-tmp
        - mountPath: /mnt/disk0
          name: ybjp2--northeast-1d-zlzk-datadir0
        - mountPath: /opt/certs/yugabyte
          name: ybjp2--northeast-1d-zlzk-yb-tserver-tls-cert
          readOnly: true
      dnsPolicy: ClusterFirst

```
Also the service named `ybjp2--northeast-1d-zlzk-yb-tservers` 
```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: yb-tserver
    chart: yugabyte
    component: yugabytedb
    heritage: Helm
    release: ybjp2--northeast-1d-zlzk
    service-type: headless
  name: ybjp2--northeast-1d-zlzk-yb-tservers
  namespace: yb-japan
  resourceVersion: "280299"
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: grpc-ybc-port
    port: 18018
    protocol: TCP
    targetPort: 18018
  - name: http-ui
    port: 9000
    protocol: TCP
    targetPort: 9000
  - name: http-ycql-met
    port: 12000
    protocol: TCP
    targetPort: 12000
  - name: http-yedis-met
    port: 11000
    protocol: TCP
    targetPort: 11000
  - name: http-ysql-met
    port: 13000
    protocol: TCP
    targetPort: 13000
  - name: tcp-rpc-port
    port: 9100
    protocol: TCP
    targetPort: 9100
  - name: tcp-yedis-port
    port: 6379
    protocol: TCP
    targetPort: 6379
  - name: tcp-yql-port
    port: 9042
    protocol: TCP
    targetPort: 9042
  - name: tcp-ysql-port
    port: 5433
    protocol: TCP
    targetPort: 5433
  selector:
    app.kubernetes.io/name: yb-tserver
    release: ybjp2--northeast-1d-zlzk
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

```

but the proxy service is missing the port `18018`

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    internal.skupper.io/controlled: "true"
    internal.skupper.io/service: ybjp2--northeast-1d-zlzk-yb-tservers
  name: ybjp2--northeast-1d-zlzk-yb-tservers-proxy
  namespace: yb-japan
  ownerReferences:
  - apiVersion: apps/v1
    kind: Deployment
    name: skupper-router
    uid: 113f2752-8216-416e-9ad7-bea75325c972
  resourceVersion: "280346"
  uid: 1d2e94f4-f0a1-4e3e-a9e5-25415fb310b5
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: ybjp2--northeast-1d-zlzk-yb-tservers-proxy9042
    port: 9042
    protocol: TCP
    targetPort: 9042
  - name: ybjp2--northeast-1d-zlzk-yb-tservers-proxy5433
    port: 5433
    protocol: TCP
    targetPort: 5433
  - name: ybjp2--northeast-1d-zlzk-yb-tservers-proxy9000
    port: 9000
    protocol: TCP
    targetPort: 9000
  - name: ybjp2--northeast-1d-zlzk-yb-tservers-proxy12000
    port: 12000
    protocol: TCP
    targetPort: 12000
  - name: ybjp2--northeast-1d-zlzk-yb-tservers-proxy11000
    port: 11000
    protocol: TCP
    targetPort: 11000
  - name: ybjp2--northeast-1d-zlzk-yb-tservers-proxy13000
    port: 13000
    protocol: TCP
    targetPort: 13000
  - name: ybjp2--northeast-1d-zlzk-yb-tservers-proxy9100
    port: 9100
    protocol: TCP
    targetPort: 9100
  - name: ybjp2--northeast-1d-zlzk-yb-tservers-proxy6379
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    internal.skupper.io/service: ybjp2--northeast-1d-zlzk-yb-tservers
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

**How To Reproduce**

Create a statefulset with 2 container, each of them exposing his own port.

**Expected behavior**
I would have expected `18018` to be also exposed by skupper.

**Environment details**
 - Skupper CLI: 1..5.3
 - Platform: Kubernetes 1.27

**Additional context**

### PR DESCRIPTION
**Pull request by grs**
Definition monitor should deduce ports for statefulset from the service associated with that statefulset (as the cli does already).

Fixes #1379

### CODE REVIEW

File: cmd/service-controller/definition_monitor.go [hunk 1]
```diff
@@ -154,6 +154,31 @@ func (m *DefinitionMonitor) runDefinitionMonitor() {
...
+	}
+	ports := map[int]int{}
+	for _, port := range service.Spec.Ports {
+		if port.TargetPort.IntValue() != 0 && int(port.Port) != port.TargetPort.IntValue() {
+			// TODO: handle string ports
+			ports[int(port.Port)] = port.TargetPort.IntValue()
+		} else {
+			ports[int(port.Port)] = int(port.Port)
+		}
+	}
```
Comment (fgiorgetti) [inline cmd/service-controller/definition_monitor.go:178]: Can it be replaced by `kube.GetServicePortMap()`?

**Review by nluaces — APPROVED** [review]

**Review by fgiorgetti — APPROVED** [review]
