### PR TITLE
Fix the early parsing of platform flag in init()

### LINKED ISSUE #1147: Platform flag not working as expected when exposing a resource in Skupper
## Expected Behavior
I was using podman to run a posgresql database, and did not set up the `SKUPPER_PLATFORM` environment variable.
After creating a skupper site with `--platform podman`, I used the same flag to expose the database into the VAN:
```
skupper expose host  database --address localhost --port 5432 --platform podman
```

## Current Behavior
It did not expose the database because it didn't recognize the target type host, but the command accepts the flag --platform.
After that, I exported SKUPPER_PLATFORM with the podman value, exposed the database with 

`skupper expose host  database --address localhost --port 5432`

and it worked fine.

## Failure Information 
```
skupper expose host  database --address localhost --port 5432 --platform podman                 
Error: target type must be one of: [deployment, statefulset, pods, service, deploymentconfig]
[...]
```

### Context
* skupper version: 1.4.0-rc4

### PR DESCRIPTION
**Pull request by gabordozsa**
The parsing of `--platform` happens very early in the `init()` in order to decide which type of client to instantiate. However, no other flags are defined yet at that point. This causes the parsing to fail if any other flag is encountered in the command line before the `--platform` one (and the code then falls back to the default Kubernetes platform). 

Fixes #1147

### CODE REVIEW

File: cmd/skupper/skupper.go [hunk 1]
```diff
@@ -1039,12 +1039,34 @@ func addCommands(skupperCli SkupperClient, rootCmd *cobra.Command, cmds ...*cobr
...
+	initWrapper(os.Args)
+}
+
+func initWrapper(args []string) {
 	rootCmd = &cobra.Command{Use: "skupper"}
 	routev1.AddToScheme(scheme.Scheme)
 
-	rootCmd.PersistentFlags().StringVarP(&config.Platform, "platform", "", "", "The platform type to use [kubernetes, podman]")
-	rootCmd.ParseFlags(os.Args)
+	rootCmd.PersistentFlags().StringVarP(&config.Platform, "platform", "", "", "The platform type t [kubernetes, podman]")
```
Comment (lynnemorrison) [inline cmd/skupper/skupper.go:1067]: looks like "to use" was accidently cut

Comment (gabordozsa) [reply cmd/skupper/skupper.go]: Ops, good catch! Fixed.

**Comment by fgiorgetti** [comment]
I believe it also fixes #1312.

**Review by grs — APPROVED** [review]

**Review by fgiorgetti — APPROVED** [review]

**Review by nluaces — APPROVED** [review]

**Review by c-kruse — APPROVED** [review]

**Review by ajssmith — APPROVED** [review]
