### PR TITLE
Fixed version in update test

### LINKED ISSUE #1707: Test failure — update_v1_5_4_test — assertion AppliesTo(test.curVersion
**Describe the bug**
The test `TestSkupperNetworkStatusVolumeUpdate/older-version` is failing consistently since Sep/24, with the following error, when executed on main:

```
23:41:10  === RUN   TestSkupperNetworkStatusVolumeUpdate/older-version
23:41:10      update_v1_5_4_test.go:78: New version: 1.5.3 - current mock site version: 1.5.4
23:41:10      update_v1_5_4_test.go:81: assertion failed: expression is false: updateSkupperNetworkVolumeTask.AppliesTo(test.curVersion) == test.applies
```

**How To Reproduce**

Run the system tests against main; not sure if -use-cluster comes into play, but it was used when the test failed.

**Expected behavior**

Test pass :)

**Environment details**
 - Skupper CLI: main (built)
 - Skupper Operator (if applicable): n/a
 - Platform: Openshift 4.12, 4.16

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by fgiorgetti**
Fixes #1707

### CODE REVIEW

File: pkg/domain/podman/update_v1_6_0_test.go [hunk 1]
```diff
@@ -36,27 +36,27 @@ func TestSkupperNetworkStatusVolumeUpdate(t *testing.T) {
...
 			curVersion: "1.5.3",
-			version:    "1.5.4",
+			version:    "1.6.0",
 			applies:    true,
 			changed:    false,
 		},
 		{
 			name:       "older-version",
-			curVersion: "1.5.4",
+			curVersion: "1.6.0",
```
Comment (hash-d) [inline pkg/domain/podman/update_v1_6_0_test.go:52]: So, the volume change was introduced in 1.6, not 1.5, and therefore both the listed version and file name are changing in this PR, is that correct?

**Review by hash-d — APPROVED** [review]
I have re-run the two tests that failed, pointing to your branch, and they were successful.

File: pkg/domain/podman/update_v1_6_0_test.go (hunk 1 above)
Comment (fgiorgetti) [reply pkg/domain/podman/update_v1_6_0_test.go:52]: That's right. This change was planned to land as part of 1.5.4,
but it ended up being part of the 1.6.0.
