### PR TITLE
Fixes #2161 - Properly protect only the initial-config listeners.

### LINKED ISSUE #2161: RouterAccess cannot create "normal" ingresses
**Describe the bug**
RouterAccess only honors "inter-router" and "edge" roles for router listeners.  It should also be usable for "normal" role listeners/ingresses.

**How To Reproduce**
Apply the following yaml to a running V2 site:
```
apiVersion: skupper.io/v2alpha1
kind: RouterAccess
metadata:
  name: test-access
spec:
  generateTlsCredentials: true
  issuer: skupper-site-ca
  roles:
  - name: normal
    port: 20002
  tlsCredentials: skupper-site-server
```

**Expected behavior**
I expect an ingress to be created for test-access and the router configuration to be updated with a normal-mode listener on port 20002.

The ingress _is_ created, but the listener is not.

**Environment details**
 - Skupper CLI: N/A
 - Skupper Operator (if applicable): main branch (6a81e6f62c06217642aa5172b7a4b6408d208aa4)
 - Platform: Openshift

**Additional context**
None.

### PR DESCRIPTION
**Pull request by ted-ross**
The old code assumed that all normal-role listeners come from the initial configuration. This does not allow for the possibility of creating normal-role RouterAccess resources. This fix makes "protected" status more explicit for listeners.

### CODE REVIEW

File: internal/qdr/qdr.go [hunk 1]
```diff
@@ -824,8 +824,14 @@ func (r *RouterConfig) UpdateConfigMap(configmap *corev1.ConfigMap) (bool, error
 
 type ListenerPredicate func(Listener) bool
 
-func IsNotNormalListener(l Listener) bool {
-	return l.Role != "normal" && l.Role != ""
+func IsNotProtectedListener(l Listener) bool {
```
Comment (ganeshmurthy) [inline internal/qdr/qdr.go:827]:
```suggestion
func IsProtectedListener(l Listener) bool {
```

Comment (ganeshmurthy) [reply internal/qdr/qdr.go:827]: The function name `IsProtectedListener` makes it much easier for me to understand the code. wdyt ?

Comment (ted-ross) [reply internal/qdr/qdr.go:827]: I agree, but that function is used in a filter that includes list objects in which the filter function returns true.  I did not change the "polarity" of the original function.

**Review by ganeshmurthy — APPROVED** [review]
