### PR TITLE
Fix to remove headless proxy service

### LINKED ISSUE #1199: Exposed statefulset services dont get deleted after unexposing
Hi,

On Version 1.4.1, When a stateful set is exposed and later unexposed, The *-proxy service that gets created doesn't get cleaned up on the local site and the service associated with the statefulset on the remote site also doest get cleaned up.

We had to manually clear these services before exposing the statefulset again.

steps:

Deploy a statefulset 
expose the stateful set using skupper cli, skupper expose statefulset name
notice a service called statefulsetname-proxy get created on the localsite and a sync'd service on the remote site
run skupper service delete servicename
notice statefulsetname-proxy on the localsite and  sync'd service on the remote site doesnt get cleaned up.

### PR DESCRIPTION
**Pull request by fgiorgetti**
Fixes #1199.

### CODE REVIEW

**Review by grs — APPROVED** [review]

File: cmd/service-controller/controller.go [hunk 1]
```diff
@@ -661,7 +661,26 @@ func (c *Controller) updateServiceSync(defs *corev1.ConfigMap) {
...
+	err := c.vanClient.KubeClient.AppsV1().StatefulSets(c.vanClient.Namespace).Delete(context.TODO(), statefulset.ObjectMeta.Name, metav1.DeleteOptions{})
+	if err != nil {
+		event.Recordf(ServiceControllerError, "Error deleting headless proxy %q: %s", statefulset.Name, err)
+		return err
+	}
+	event.Recordf(ServiceControllerEvent, "Deleted headless proxy %q", statefulset.Name)
+	svcName := statefulset.Spec.ServiceName
+	svc, found, err := c.GetService(svcName)
+	if !found {
+		event.Recordf(ServiceControllerError, "Headless proxy service %q not found", svcName)
```
Comment (nluaces) [inline cmd/service-controller/controller.go:673]: Same here with `RecordWarningEvent`

File: cmd/service-controller/controller.go [hunk 2]
```diff
@@ -661,7 +661,26 @@ func (c *Controller) updateServiceSync(defs *corev1.ConfigMap) {
...
+	} else if err != nil {
+		event.Recordf(ServiceControllerError, "Error retrieving headless proxy service %q: %s", svcName, err)
+	} else if c.IsOwned(svc) {
+		if err = kube.DeleteService(svcName, c.vanClient.Namespace, c.vanClient.KubeClient); err != nil {
+			event.Recordf(ServiceControllerError, "Error deleting headless proxy service %q: %s", statefulset.Name, err)
+			return err
+		}
+		event.Recordf(ServiceControllerEvent, "Deleted headless proxy service %q", statefulset.Name)
```
Comment (nluaces) [inline cmd/service-controller/controller.go:681]: Same here but this time with `RecordNormalEvent`

File: cmd/service-controller/controller.go [hunk 3]
```diff
@@ -661,7 +661,26 @@ func (c *Controller) updateServiceSync(defs *corev1.ConfigMap) {
...
+		event.Recordf(ServiceControllerError, "Error deleting headless proxy %q: %s", statefulset.Name, err)
+		return err
+	}
+	event.Recordf(ServiceControllerEvent, "Deleted headless proxy %q", statefulset.Name)
+	svcName := statefulset.Spec.ServiceName
+	svc, found, err := c.GetService(svcName)
+	if !found {
+		event.Recordf(ServiceControllerError, "Headless proxy service %q not found", svcName)
+	} else if err != nil {
+		event.Recordf(ServiceControllerError, "Error retrieving headless proxy service %q: %s", svcName, err)
```
Comment (nluaces) [inline cmd/service-controller/controller.go:675]: Same here with `RecordWarningEvent`

**Review by nluaces — APPROVED** [review]
