### PR TITLE
Fix test for Podman 5, where an empty hostIp is now listed as 0.0.0.0

### LINKED ISSUE #1841: Test failure due to Podman version
**Describe the bug**

`TestHelloWorldCLIOnPodman/service-create-bind` fails on Podman version 5, with an error such as below:

    2024/12/11 11:42:06 service-create-bind has failed, exiting
    2024/12/11 11:42:06 STDOUT:
    Services exposed through Skupper:
    ├─ hello-world-backend:8080 (tcp)
    │  ╰─ Host ports:
    │     ╰─ ip: 0.0.0.0 - ports: 8081 -> 8080
    ╰─ hello-world-frontend:8080 (tcp)
       ╰─ Host ports:
          ╰─ ip: 0.0.0.0 - ports: 8080 -> 8080
    2024/12/11 11:42:06 STDERR:
        tester.go:161: Error: context deadline exceeded

On investigation, it was determined that the way Podman reports the `HostIp` field changed.

On version 4.x, when a container ports bound to all interfaces, on inspection its `HostIp` field would be empty:

               "PortBindings": {                                                                                                                                                                                                              
                    "8080/tcp": [                                                                                                                                                                                                             
                         {                                                                                                                                                                                                                    
                              "HostIp": "",                                                                            
                              "HostPort": "8080"                                                                                                                                                                                              
                         }                                                                                                                                                                                                                    
                    ]                                                                                                                                                                                                                         
               },                                                                                                                                                                                                                             

On version 5.x that changed; 

               "PortBindings": {
                    "8000/tcp": [
                         {
                              "HostIp": "0.0.0.0",
                              "HostPort": "8001"
                         }
                    ]
               },


**How To Reproduce**

    $ skupper init --platform podman
    Skupper is now installed for user 'x'.  Use 'skupper status' to get more information.
    $ skupper --platform podman service create asdf 8000 --protocol tcp --container-name asdf --host-port 8000:8001

On the next steps, the result will be different between Podman 4 and 5.

Podman 4.9.4:

    $ skupper --platform podman service status
    Services exposed through Skupper:
    ╰─ asdf:8000 (tcp)
       ╰─ Host ports:
          ╰─ ip: * - ports: 8001 -> 8000
    $ podman container inspect asdf | grep HostIp
                              "HostIp": "",
                              "HostIp": "",

Podman 5.2.2:

    $ skupper --platform podman service status
    Services exposed through Skupper:
    ╰─ asdf:8000 (tcp)
       ╰─ Host ports:
          ╰─ ip: 0.0.0.0 - ports: 8001 -> 8000
    $ podman container inspect asdf | grep HostIp
                                  "HostIp": "0.0.0.0",
                                  "HostIp": "0.0.0.0",
    
The way `service. StatusTester` works, it expected either that literal asterisk, or a specific host configured on the test table.

The Podman change reflected on the Skupper output, and both are only informational.  We did not observe any impacts on skupper operation itself.

**Expected behavior**

The test should pass on Podman 5.

**Environment details**
 - Skupper CLI:1.5.5, 1.4.X
 - Skupper Operator (if applicable): N/A
 - Platform: podman

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by hash-d**
Fixes #1841 

Also includes a fix from main (4b0884f and 03b88ad) which was hitting the CircleCI checks

### CODE REVIEW

**Review by granzoto — APPROVED** [review]
LGTM. Already tested with the fix with success

File: test/utils/k8s/job.go [hunk 1]
```diff
@@ -175,19 +175,29 @@ func WaitForJob(ns string, kubeClient kubernetes.Interface, jobName string, time
...
-				if job.Status.Conditions[0].Type == batchv1.JobComplete {
-					fmt.Println("Job Successful!")
-					return job, nil
-				} else if job.Status.Conditions[0].Type == batchv1.JobFailed {
-					statusJson, _ := json.Marshal(job.Status)
-					fmt.Printf("Job failed?, status = %v\n", string(statusJson))
-					return job, fmt.Errorf("Job failed. Status: %s", string(statusJson))
+				for _, condition := range job.Status.Conditions {
+					switch condition.Type {
+					case batchv1.JobComplete:
```
Comment (fgiorgetti) [inline test/utils/k8s/job.go:189]: Here we possibly have an issue similar to what we had in a retry function fixed recently.
The right thing to do is to go through all conditions first, before returning an error on the first
found failed condition. That is because the order is not guaranteed, so the complete might show
after a failed condition.

**Review by fgiorgetti — APPROVED** [review]

File: test/utils/k8s/job.go (hunk 1 above)
Comment (hash-d) [reply test/utils/k8s/job.go:189]: @fgiorgetti  as we discussed, the Complete and Failed conditions are terminal conditions, and mutually exclusive.

https://kubernetes.io/docs/concepts/workloads/controllers/job/#terminal-job-conditions
