### PR TITLE
use service controller deployment as event source

### LINKED ISSUE #1323: Service Controller failing to create k8s Events
**Describe the bug**
The skupper service controller is logging a failure to write events when deployed without the console.

```
E1214 16:25:45.094731       1 event.go:273] Unable to write event: '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:".17a0bf6df167801f", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Service", Namespace:"", Name:"", UID:"", APIVersion:"v1", ResourceVersion:"", FieldPath:""}, Reason:"ServiceSyncEvent", Message:"Service sync receiver connection to amqps://skupper-router-local.withoutconsole.svc.cluster.local:5671 established", Source:v1.EventSource{Component:"skupper", Host:""}, FirstTimestamp:time.Date(2023, time.December, 14, 16, 25, 38, 68480031, time.Local), LastTimestamp:time.Date(2023, time.December, 14, 16, 25, 38, 68480031, time.Local), Count:1, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'can't create an event with namespace 'default' in namespace 'withoutconsole''(may retry after sleeping)
E1214 16:25:55.096072       1 event.go:273] Unable to write event: '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:".17a0bf6df167801f", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Service", Namespace:"", Name:"", UID:"", APIVersion:"v1", ResourceVersion:"", FieldPath:""}, Reason:"ServiceSyncEvent", Message:"Service sync receiver connection to amqps://skupper-router-local.withoutconsole.svc.cluster.local:5671 established", Source:v1.EventSource{Component:"skupper", Host:""}, FirstTimestamp:time.Date(2023, time.December, 14, 16, 25, 38, 68480031, time.Local), LastTimestamp:time.Date(2023, time.December, 14, 16, 25, 38, 68480031, time.Local), Count:1, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'can't create an event with namespace 'default' in namespace 'withoutconsole''(may retry after sleeping)
E1214 16:26:05.096629       1 event.go:273] Unable to write event: '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:".17a0bf6df167801f", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Service", Namespace:"", Name:"", UID:"", APIVersion:"v1", ResourceVersion:"", FieldPath:""}, Reason:"ServiceSyncEvent", Message:"Service sync receiver connection to amqps://skupper-router-local.withoutconsole.svc.cluster.local:5671 established", Source:v1.EventSource{Component:"skupper", Host:""}, FirstTimestamp:time.Date(2023, time.December, 14, 16, 25, 38, 68480031, time.Local), LastTimestamp:time.Date(2023, time.December, 14, 16, 25, 38, 68480031, time.Local), Count:1, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'can't create an event with namespace 'default' in namespace 'withoutconsole''(may retry after sleeping)
E1214 16:26:15.097808       1 event.go:273] Unable to write event: '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:".17a0bf6df167801f", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Service", Namespace:"", Name:"", UID:"", APIVersion:"v1", ResourceVersion:"", FieldPath:""}, Reason:"ServiceSyncEvent", Message:"Service sync receiver connection to amqps://skupper-router-local.withoutconsole.svc.cluster.local:5671 established", Source:v1.EventSource{Component:"skupper", Host:""}, FirstTimestamp:time.Date(2023, time.December, 14, 16, 25, 38, 68480031, time.Local), LastTimestamp:time.Date(2023, time.December, 14, 16, 25, 38, 68480031, time.Local), Count:1, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'can't create an event with namespace 'default' in namespace 'withoutconsole''(may retry after sleeping)
E1214 16:26:25.098153       1 event.go:273] Unable to write event: '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:".17a0bf6df167801f", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Service", Namespace:"", Name:"", UID:"", APIVersion:"v1", ResourceVersion:"", FieldPath:""}, Reason:"ServiceSyncEvent", Message:"Service sync receiver connection to amqps://skupper-router-local.withoutconsole.svc.cluster.local:5671 established", Source:v1.EventSource{Component:"skupper", Host:""}, FirstTimestamp:time.Date(2023, time.December, 14, 16, 25, 38, 68480031, time.Local), LastTimestamp:time.Date(2023, time.December, 14, 16, 25, 38, 68480031, time.Local), Count:1, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'can't create an event with namespace 'default' in namespace 'withoutconsole''(may retry after sleeping)
E1214 16:26:35.099177       1 event.go:273] Unable to write event: '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:".17a0bf6df167801f", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Service", Namespace:"", Name:"", UID:"", APIVersion:"v1", ResourceVersion:"", FieldPath:""}, Reason:"ServiceSyncEvent", Message:"Service sync receiver connection to amqps://skupper-router-local.withoutconsole.svc.cluster.local:5671 established", Source:v1.EventSource{Component:"skupper", Host:""}, FirstTimestamp:time.Date(2023, time.December, 14, 16, 25, 38, 68480031, time.Local), LastTimestamp:time.Date(2023, time.December, 14, 16, 25, 38, 68480031, time.Local), Count:1, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'can't create an event with namespace 'default' in namespace 'withoutconsole''(may retry after sleeping)
```

**How To Reproduce**
`skupper init` in some kubernetes namespace besides default.

Wait for init to finish, then watch the logs for the service controller: `kubectl logs deployments/skupper-service-controller`.

Observe that the `ServiceSyncEvent`s do not get published: `kubectl events | grep ServiceSyncEvent`

**Expected behavior**
I would expect ServiceSyncEvents to be published. I think we are just associating them with the wrong resource.

When deployed with the console, events are published associated with service/skupper
```
$ kubectl -n withconsole events --for Service/skupper
LAST SEEN   TYPE      REASON             OBJECT            MESSAGE
17m         Warning   AllocationFailed   Service/skupper   Failed to allocate IP for "withconsole/skupper": no available IPs
16m         Normal    IPAllocated        Service/skupper   Assigned IP ["192.168.11.21"]
16m         Normal    ServiceSyncEvent   Service/skupper   Service sync receiver connection to amqps://skupper-router-local.withconsole.svc.cluster.local:5671 established
16m         Normal    ServiceSyncEvent   Service/skupper   Service sync sender connection to amqps://skupper-router-local.withconsole.svc.cluster.local:5671 established
```

**Environment details**
 - Skupper CLI: 1.5.1
 - Skupper Operator (if applicable): N/A
  - Platform: kubernetes

**Additional context**

### PR DESCRIPTION
**Pull request by nluaces**
Fixes #1323

### CODE REVIEW

File: pkg/kube/events.go [hunk 1]
```diff
@@ -54,12 +54,19 @@ func NewSkupperEventRecorder(namespace string, cli kubernetes.Interface) *Skuppe
 	kubeEventRecorder := eventBroadcaster.NewRecorder(
 		scheme.Scheme,
 		v1.EventSource{
-			Component: types.ControllerServiceName})
-	service, _ := cli.CoreV1().Services(namespace).Get(context.TODO(), types.ControllerServiceName, metav1.GetOptions{})
+			Component: types.ControllerDeploymentName})
+	deployment, _ := cli.AppsV1().Deployments(namespace).Get(context.TODO(), types.ControllerDeploymentName, metav1.GetOptions{})
```
Comment (grs) [inline pkg/kube/events.go:58]: This assumes that the service-controller deployment is always present in the namespace for which the event recorder is being used. That is true now, but might not always be so.

One option could be to have the source provided as an argument to this function, and then to have the service-controller (which I think is at present the only user of the function) provide an object ref to its own deployment.

Comment (nluaces) [reply pkg/kube/events.go]: Makes sense! updated in 6b750cc0e2b00989847c9bf47d4e4a207903dc07

File: cmd/service-controller/controller.go [hunk 2]
```diff
@@ -188,7 +188,14 @@ func NewController(cli *client.VanClient, origin string, tlsConfig *certs.TlsCon
 	}
 
 	if enableSkupperEvents {
-		controller.eventHandler = kube.NewSkupperEventRecorder(cli.Namespace, cli.KubeClient)
+		deployment, _ := kube.GetDeployment(types.ControllerDeploymentName, cli.Namespace, cli.KubeClient)
```
Comment (grs) [inline cmd/service-controller/controller.go:191]: If this results in an error, deployment might be nil and the subsequent line would cause a crash. Might be nicer to fail with a clear error?

Comment (nluaces) [reply cmd/service-controller/controller.go:191]: This is being executed inside the service-controller deployment that is running, so it should not be nil...Nevertheless,  the client could fail for any other reason, so I agree on that.

Comment (nluaces) [reply cmd/service-controller/controller.go]: updated in 42c9c91129661fda0d7cd12114be47febf6e5fa7

**Review by grs — APPROVED** [review]

**Review by ajssmith — APPROVED** [review]
